# Generated by Django 5.0.7 on 2024-07-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(choices=[('Appetizers', 'Appetizers'), ('Main Courses', 'Main Courses'), ('Desserts', 'Desserts'), ('Drinks', 'Drinks'), ('Others', 'Others')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
